services:
  leader:
    build:
      context: ./leader
      dockerfile: Dockerfile
    container_name: lunaricorn-leader
    ports:
      - "8001:8000"
    volumes:
      - ${LUNARICORN_HOME}/leader_data:/opt/lunaricorn/leader_data
    environment:
      - PYTHONUNBUFFERED=1
      - db_type=postgresql
      - db_host=lunaricorn-pg
      - db_port=5432
      - db_user=lunaricorn
      - db_password=${LUNARICORN_PASSWORD}
      - db_name=lunaricorn
      - db_schema=lunaricorn
    networks:
      - lunaricorn-network
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: lunaricorn-portal
    ports:
      - "8002:8000"
    volumes:
      - ${LUNARICORN_HOME}/portal_data:/opt/lunaricorn/portal_data
    environment:
      - PYTHONUNBUFFERED=1
      - CLUSTER_LEADER_URL=http://leader:8000/
    networks:
      - lunaricorn-network
    depends_on:
      leader:
          condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  loki:
    image: grafana/loki:main-3fc14f7
    container_name: lunaricorn-loki
    ports:
      - "8004:3100"    # Loki API (прием логов)
    volumes:
      - ./data/loki:/etc/loki
      - ${LUNARICORN_HOME}/loki-storage:/loki
    command:
      - "-config.file=/etc/loki/local-config.yaml"
      - "-config.expand-env=true"
    restart: unless-stopped
    networks:
      - lunaricorn-network

  grafana:
    image: grafana/grafana:latest
    container_name: lunaricorn-grafana
    ports:
      - "8005:3000"    # Grafana UI (просмотр логов)
    volumes:
      - ${LUNARICORN_HOME}/grafana-data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true     # Включает анонимный вход
      - GF_AUTH_DISABLE_LOGIN_FORM=false   # Отключает форму входа  
    restart: unless-stopped
    depends_on:
      - loki
    networks:
      - lunaricorn-network

  pg:
    build:
      context: ./data/pg
      dockerfile: Dockerfile
    container_name: lunaricorn-pg
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_ROOT_PASSWORD}
      - POSTGRES_DB=postgres
      - LUNARICORN_PASSWORD=${LUNARICORN_PASSWORD}
    volumes:
      - ${LUNARICORN_HOME}/pg_data:/var/lib/postgresql
    networks:
      - lunaricorn-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  orb:
    build:
      context: ./orb
      dockerfile: Dockerfile
    container_name: lunaricorn-orb
    ports:
      - "${ORB_API_PORT}:8080"
    volumes:
      - ${LUNARICORN_HOME}/orb_data:/opt/lunaricorn/orb/data
      - ${LUNARICORN_HOME}/orb_storage:/opt/lunaricorn/orb/file_storage
    environment:
      - PYTHONUNBUFFERED=1
      - CLUSTER_LEADER_URL=http://leader:8000/
      - SIGNALING_HOST=signaling
      - ORB_API_PORT=8080
      - SIGNALING_REQ=5555
      - SIGNALING_PUB=5556
      - SIGNALING_API=5557
      - db_type=postgresql
      - db_host=lunaricorn-pg
      - db_port=5432
      - db_user=lunaricorn
      - db_password=${LUNARICORN_PASSWORD}
      - db_name=lunaricorn
      - db_schema=lunaricorn
    networks:
      - lunaricorn-network
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
      leader:
        condition: service_healthy

  signaling:
    build:
      context: ./signaling
      dockerfile: Dockerfile
    container_name: lunaricorn-signaling
    ports:
      - "5555:5555" # REQ-REP port
      - "5556:5556" # PUB-SUB port
      - "5557:5557" # HTTP api port
    volumes:
      - ${LUNARICORN_HOME}/signaling_data:/opt/lunaricorn/signaling_data
    environment:
      - PYTHONUNBUFFERED=1
      - CLUSTER_LEADER_URL=http://leader:8000/
      - db_type=postgresql
      - db_host=lunaricorn-pg
      - db_port=5432
      - db_user=lunaricorn
      - db_password=${LUNARICORN_PASSWORD}
      - db_name=lunaricorn
      - db_schema=lunaricorn
    networks:
      - lunaricorn-network
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
      leader:
        condition: service_healthy

networks:
  lunaricorn-network:
    driver: bridge
    name: lunaricorn-network
volumes:
  loki-rules: # Docker сам создаст том с правильными правами